[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram-dialog==2.2.0",
    "aiogram>=3.21.0",
    "flask>=3.1.1",
    "aiohttp>=3.12.14",
]
